spring:
  application:
    name: request-processing-service

  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    consumer:
      group-id: account-group
      auto-offset-reset: earliest
    template:
      default-topic: topic